language: python
python:
  - "3.6.0"
services: postgresql
addons:
  postgresql: '9.6'
env:
   - DATABASE_URL=postgres://postgres@localhost/carouseldb
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - psql -c "CREATE DATABASE carouseldb;" -U postgres
  - python manage.py migrate
  - python manage.py collectstatic --no-input
script:
  - coverage run --source='django_carousel' manage.py test
  - flake8
  - pipenv run python manage.py test

before_install:
  - pip install coveralls
after_success:
  - coveralls